### ISSUE TITLE
Change repository name and publish to npm

### ISSUE THREAD

**Issue by samueljoos** [Prophets/chef-patissier#6]
Ok, I need an opinion how are we going to move this repo to the dameblanche repo?

The options I see are:
1. rename the current dameblanche repo to dameblanche-legacy and rename this one to dameblanche
2. use a different name for this project and leave the old dameblanch project as is. (discoballs for example)
3. copy the files of this repo into the dameblanche repo

What do you think @thomasmattheussen @vsteenhoudt ?

**Comment by thomasmattheussen** [comment]
I'd advocate for option 1. This keeps all git history for both projects, and doesn't force us to come up with another name :)
